import type {
  AuditEvent,
  AuthUser,
  CombinedSection,
  Conflict,
  Course,
  DashboardMetrics,
  Department,
  Faculty,
  Holiday,
  LockedSlot,
  ReportSummary,
  Room,
  Section,
  Timeslot,
  TimetableEntry,
  TimetableVersion,
} from "@/lib/types"

export const demoUser: AuthUser = {
  id: "admin-01",
  name: "Ayesha Rahman",
  email: "admin@sau.edu",
  role: "SUPER_ADMIN",
  department: "University Scheduling Office",
}

export const departments: Department[] = [
  { id: "cse", name: "Computer Science", shortCode: "CSE", campus: "Main Block", sections: 4 },
  { id: "ece", name: "Electrical Engineering", shortCode: "ECE", campus: "North Wing", sections: 3 },
  { id: "me", name: "Mechanical Engineering", shortCode: "ME", campus: "Central Labs", sections: 2 },
]

export const faculty: Faculty[] = [
  {
    id: "fac-001",
    name: "Dr. Farhan Alam",
    designation: "Professor",
    departmentId: "cse",
    maxPeriodsPerDay: 4,
    weeklyLoad: 14,
    availability: "Mon-Thu, morning heavy",
    preferences: ["AI Lab", "P1", "P2"],
    status: "balanced",
  },
  {
    id: "fac-002",
    name: "Prof. Sara Joseph",
    designation: "Associate Professor",
    departmentId: "cse",
    maxPeriodsPerDay: 4,
    weeklyLoad: 17,
    availability: "Mon-Fri, all day",
    preferences: ["P3", "P4"],
    status: "high_load",
  },
  {
    id: "fac-003",
    name: "Dr. Ibrahim Khan",
    designation: "Assistant Professor",
    departmentId: "ece",
    maxPeriodsPerDay: 3,
    weeklyLoad: 11,
    availability: "Tue-Fri, no P7",
    preferences: ["Circuits Lab"],
    status: "limited",
  },
  {
    id: "fac-004",
    name: "Prof. Nidhi Sharma",
    designation: "Professor",
    departmentId: "ece",
    maxPeriodsPerDay: 4,
    weeklyLoad: 13,
    availability: "Mon-Thu, balanced",
    preferences: ["P1", "P5"],
    status: "balanced",
  },
  {
    id: "fac-005",
    name: "Dr. Zubair Hussain",
    designation: "Lab Coordinator",
    departmentId: "me",
    maxPeriodsPerDay: 4,
    weeklyLoad: 12,
    availability: "Mon-Fri, practical slots",
    preferences: ["Manufacturing Lab", "P6", "P7"],
    status: "balanced",
  },
]

export const rooms: Room[] = [
  { id: "rm-101", name: "A-101", block: "Academic Block A", capacity: 60, roomType: "CLASSROOM", utilization: 82 },
  { id: "rm-203", name: "A-203", block: "Academic Block A", capacity: 48, roomType: "CLASSROOM", utilization: 68 },
  { id: "rm-305", name: "B-305", block: "Engineering Block", capacity: 120, roomType: "CLASSROOM", utilization: 74 },
  { id: "lab-ai", name: "AI Lab", block: "Innovation Center", capacity: 36, roomType: "LAB", utilization: 86 },
  { id: "lab-circuits", name: "Circuits Lab", block: "North Wing", capacity: 32, roomType: "LAB", utilization: 71 },
  { id: "lab-manufacturing", name: "Manufacturing Lab", block: "Central Labs", capacity: 28, roomType: "LAB", utilization: 79 },
]

export const sections: Section[] = [
  { id: "cse-3a", name: "CSE 3A", departmentId: "cse", semester: 3, studentCount: 54, advisor: "Dr. Farhan Alam", compactness: 87 },
  { id: "cse-3b", name: "CSE 3B", departmentId: "cse", semester: 3, studentCount: 50, advisor: "Prof. Sara Joseph", compactness: 82 },
  { id: "cse-5a", name: "CSE 5A", departmentId: "cse", semester: 5, studentCount: 44, advisor: "Dr. Farhan Alam", compactness: 90 },
  { id: "ece-3a", name: "ECE 3A", departmentId: "ece", semester: 3, studentCount: 46, advisor: "Dr. Ibrahim Khan", compactness: 78 },
  { id: "ece-5a", name: "ECE 5A", departmentId: "ece", semester: 5, studentCount: 38, advisor: "Prof. Nidhi Sharma", compactness: 81 },
  { id: "me-3a", name: "ME 3A", departmentId: "me", semester: 3, studentCount: 34, advisor: "Dr. Zubair Hussain", compactness: 84 },
]

export const courses: Course[] = [
  {
    id: "cs301",
    code: "CS301",
    name: "Design and Analysis of Algorithms",
    departmentId: "cse",
    semester: 3,
    theoryHours: 3,
    practicalHours: 0,
    labRequired: false,
    facultyId: "fac-002",
    sectionIds: ["cse-3a", "cse-3b"],
    status: "scheduled",
  },
  {
    id: "cs315",
    code: "CS315",
    name: "Database Systems",
    departmentId: "cse",
    semester: 3,
    theoryHours: 2,
    practicalHours: 2,
    labRequired: true,
    facultyId: "fac-001",
    sectionIds: ["cse-3a", "cse-3b"],
    status: "review",
  },
  {
    id: "cs501",
    code: "CS501",
    name: "Machine Learning",
    departmentId: "cse",
    semester: 5,
    theoryHours: 3,
    practicalHours: 2,
    labRequired: true,
    facultyId: "fac-001",
    sectionIds: ["cse-5a"],
    status: "draft",
  },
  {
    id: "ee301",
    code: "EE301",
    name: "Signals and Systems",
    departmentId: "ece",
    semester: 3,
    theoryHours: 3,
    practicalHours: 0,
    labRequired: false,
    facultyId: "fac-003",
    sectionIds: ["ece-3a"],
    status: "scheduled",
  },
  {
    id: "ee326",
    code: "EE326",
    name: "Circuits Laboratory",
    departmentId: "ece",
    semester: 3,
    theoryHours: 0,
    practicalHours: 2,
    labRequired: true,
    facultyId: "fac-003",
    sectionIds: ["ece-3a"],
    status: "review",
  },
  {
    id: "ee504",
    code: "EE504",
    name: "Power Electronics",
    departmentId: "ece",
    semester: 5,
    theoryHours: 3,
    practicalHours: 1,
    labRequired: true,
    facultyId: "fac-004",
    sectionIds: ["ece-5a"],
    status: "scheduled",
  },
  {
    id: "me302",
    code: "ME302",
    name: "Manufacturing Processes",
    departmentId: "me",
    semester: 3,
    theoryHours: 3,
    practicalHours: 2,
    labRequired: true,
    facultyId: "fac-005",
    sectionIds: ["me-3a"],
    status: "scheduled",
  },
]

export const combinedSections: CombinedSection[] = [
  {
    id: "cmb-cs315",
    label: "CSE 3A + CSE 3B",
    courseCode: "CS315",
    semester: 3,
    sectionIds: ["cse-3a", "cse-3b"],
    combinedStudentCount: 104,
    facultyId: "fac-001",
    roomId: "rm-305",
  },
  {
    id: "cmb-foundation",
    label: "CSE 5A + ECE 5A",
    courseCode: "AI Elective",
    semester: 5,
    sectionIds: ["cse-5a", "ece-5a"],
    combinedStudentCount: 82,
    facultyId: "fac-002",
    roomId: "rm-305",
  },
]

export const timeslots: Timeslot[] = [
  { id: "p1", label: "P1", start: "08:30", end: "09:25" },
  { id: "p2", label: "P2", start: "09:30", end: "10:25" },
  { id: "p3", label: "P3", start: "10:35", end: "11:30" },
  { id: "p4", label: "P4", start: "11:35", end: "12:30" },
  { id: "lunch", label: "Lunch", start: "12:30", end: "13:20", isLunch: true },
  { id: "p5", label: "P5", start: "13:20", end: "14:15" },
  { id: "p6", label: "P6", start: "14:20", end: "15:15" },
  { id: "p7", label: "P7", start: "15:25", end: "16:20" },
]

export const holidays: Holiday[] = [
  { id: "hol-1", name: "Founders Day", date: "2026-04-12", scope: "University", impact: "Solver blocks all slots automatically." },
  { id: "hol-2", name: "Exam Buffer Day", date: "2026-05-03", scope: "Engineering Block", impact: "Only lab-intensive sections need reseating." },
  { id: "hol-3", name: "Admissions Open House", date: "2026-05-15", scope: "Main Block", impact: "Large classrooms reserved from P3 onward." },
]

export const timetableVersions: TimetableVersion[] = [
  {
    id: "ver-2026-spring-active",
    label: "Spring 2026 Active",
    departmentId: "all",
    status: "ACTIVE",
    generatedAt: "2026-04-03 11:22",
    qualityScore: 93,
    lockedSlots: 8,
    notes: "Published after final dean review.",
  },
  {
    id: "ver-2026-spring-draft",
    label: "Spring 2026 Draft",
    departmentId: "all",
    status: "DRAFT",
    generatedAt: "2026-04-03 13:05",
    qualityScore: 96,
    lockedSlots: 11,
    notes: "Includes compactness optimization and lab chaining.",
  },
  {
    id: "ver-2026-spring-archive",
    label: "Spring 2026 Archived",
    departmentId: "all",
    status: "ARCHIVED",
    generatedAt: "2026-03-29 17:42",
    qualityScore: 88,
    lockedSlots: 5,
    notes: "Pre-convocation revision snapshot.",
  },
]

export const lockedSlots: LockedSlot[] = [
  { id: "lock-1", day: "Mon", timeslotId: "p2", sectionId: "cse-3a", reason: "Faculty senate commitment", lockedBy: "Ayesha Rahman" },
  { id: "lock-2", day: "Wed", timeslotId: "p5", sectionId: "me-3a", reason: "Lab equipment calibration window", lockedBy: "Ops Team" },
]

export const editorEntries: TimetableEntry[] = [
  { id: "tte-1", day: "Mon", timeslotId: "p1", sectionId: "cse-3a", courseCode: "CS301", courseName: "Algorithms", facultyName: "Prof. Sara Joseph", roomName: "A-101", type: "THEORY" },
  { id: "tte-2", day: "Mon", timeslotId: "p2", sectionId: "cse-3a", courseCode: "CS315", courseName: "Database Systems", facultyName: "Dr. Farhan Alam", roomName: "A-203", type: "THEORY", locked: true, note: "Pinned during manual review" },
  { id: "tte-3", day: "Mon", timeslotId: "p5", sectionId: "cse-3a", courseCode: "CS315", courseName: "Database Lab", facultyName: "Dr. Farhan Alam", roomName: "AI Lab", type: "LAB", combined: true },
  { id: "tte-4", day: "Mon", timeslotId: "p6", sectionId: "cse-3a", courseCode: "CS315", courseName: "Database Lab", facultyName: "Dr. Farhan Alam", roomName: "AI Lab", type: "LAB", combined: true },
  { id: "tte-5", day: "Tue", timeslotId: "p3", sectionId: "cse-3a", courseCode: "CS301", courseName: "Algorithms", facultyName: "Prof. Sara Joseph", roomName: "A-101", type: "THEORY" },
  { id: "tte-6", day: "Tue", timeslotId: "p7", sectionId: "cse-3a", courseCode: "HS210", courseName: "Technical Communication", facultyName: "Guest Faculty", roomName: "A-203", type: "THEORY" },
  { id: "tte-7", day: "Wed", timeslotId: "p1", sectionId: "cse-5a", courseCode: "CS501", courseName: "Machine Learning", facultyName: "Dr. Farhan Alam", roomName: "A-101", type: "THEORY" },
  { id: "tte-8", day: "Wed", timeslotId: "p5", sectionId: "me-3a", courseCode: "ME302", courseName: "Manufacturing Processes", facultyName: "Dr. Zubair Hussain", roomName: "Manufacturing Lab", type: "LAB", locked: true },
  { id: "tte-9", day: "Wed", timeslotId: "p6", sectionId: "me-3a", courseCode: "ME302", courseName: "Manufacturing Processes", facultyName: "Dr. Zubair Hussain", roomName: "Manufacturing Lab", type: "LAB", locked: true },
  { id: "tte-10", day: "Thu", timeslotId: "p2", sectionId: "ece-3a", courseCode: "EE301", courseName: "Signals and Systems", facultyName: "Dr. Ibrahim Khan", roomName: "A-203", type: "THEORY" },
  { id: "tte-11", day: "Thu", timeslotId: "p5", sectionId: "ece-3a", courseCode: "EE326", courseName: "Circuits Laboratory", facultyName: "Dr. Ibrahim Khan", roomName: "Circuits Lab", type: "LAB" },
  { id: "tte-12", day: "Thu", timeslotId: "p6", sectionId: "ece-3a", courseCode: "EE326", courseName: "Circuits Laboratory", facultyName: "Dr. Ibrahim Khan", roomName: "Circuits Lab", type: "LAB" },
]

export const conflicts: Conflict[] = [
  {
    id: "conf-1",
    severity: "critical",
    title: "Combined section exceeds room capacity",
    description: "CSE 3A + CSE 3B exceeds AI Lab capacity during Monday lab block.",
    ruleCode: "HC-04",
    affected: ["CS315", "AI Lab", "CSE 3A", "CSE 3B"],
    suggestedFixes: ["Move to B-305 large hall", "Split section back into parallel labs", "Reassign to Thu P5-P6"],
    qualityImpact: -12,
    status: "open",
  },
  {
    id: "conf-2",
    severity: "high",
    title: "Faculty overload on Tuesday",
    description: "Prof. Sara Joseph is assigned five periods, breaching the configured daily cap.",
    ruleCode: "HC-09",
    affected: ["Prof. Sara Joseph", "CS301", "CS501"],
    suggestedFixes: ["Shift one theory block to Thursday P3", "Swap with Dr. Farhan Alam's advisory slot", "Increase cap after dean approval"],
    qualityImpact: -8,
    status: "open",
  },
  {
    id: "conf-3",
    severity: "medium",
    title: "Section compactness can improve",
    description: "ECE 5A has a two-period idle gap between theory and lab sessions.",
    ruleCode: "SC-01",
    affected: ["ECE 5A", "EE504"],
    suggestedFixes: ["Pull theory to P3", "Push lab to P6-P7", "Bundle with shared elective window"],
    qualityImpact: -4,
    status: "open",
  },
]

export const auditTrail: AuditEvent[] = [
  { id: "evt-1", actor: "Ayesha Rahman", action: "Published timetable", target: "Spring 2026 Active", timestamp: "13 min ago", tone: "success" },
  { id: "evt-2", actor: "Solver Worker", action: "Completed partial regenerate", target: "Draft version", timestamp: "21 min ago", tone: "info" },
  { id: "evt-3", actor: "Prof. Sara Joseph", action: "Updated availability", target: "Tuesday slots", timestamp: "48 min ago", tone: "warning" },
  { id: "evt-4", actor: "Import assistant", action: "Loaded demo dataset", target: "9 sections / 15 courses", timestamp: "1 hr ago", tone: "info" },
]

export const dashboardMetrics: DashboardMetrics = {
  solverStatus: "healthy",
  solverLabel: "Solver ready for next generate cycle",
  queueDepth: 2,
  generationProgress: 78,
  roomUtilization: 74,
  facultyLoadBalance: 88,
  unresolvedConflicts: conflicts.length,
  activeVersion: timetableVersions[0],
  draftVersion: timetableVersions[1],
  recentActions: auditTrail,
  utilizationByDepartment: [
    { label: "CSE", value: 82, emphasis: "Best lab packing" },
    { label: "ECE", value: 71, emphasis: "Needs room rebalance" },
    { label: "ME", value: 69, emphasis: "Practical heavy" },
  ],
  facultyWorkloadSnapshot: [
    { label: "Farhan", value: 14 },
    { label: "Sara", value: 17 },
    { label: "Ibrahim", value: 11 },
    { label: "Nidhi", value: 13 },
    { label: "Zubair", value: 12 },
  ],
  compactnessSnapshot: [
    { label: "CSE 3A", value: 87 },
    { label: "CSE 5A", value: 90 },
    { label: "ECE 3A", value: 78 },
    { label: "ME 3A", value: 84 },
  ],
}

export const reportSummary: ReportSummary = {
  roomUtilization: [
    { label: "Classrooms", value: 74 },
    { label: "Labs", value: 79 },
    { label: "Large Halls", value: 62 },
  ],
  facultyGaps: [
    { label: "Target", value: 5 },
    { label: "Current", value: 7 },
    { label: "Best draft", value: 4 },
  ],
  compactness: [
    { label: "Semester 3", value: 84 },
    { label: "Semester 5", value: 89 },
  ],
  exports: [
    { label: "Faculty PDF Pack", description: "Print-ready faculty schedules with department filters." },
    { label: "Section Excel Bundle", description: "Editable section-wise exports for circulation." },
    { label: "Conflict Review Memo", description: "Dean-facing summary of unresolved violations and suggestions." },
  ],
}
